---
- include_tasks: assert.yml
  tags:
    - install
    - uninstall

- include_tasks: collect_info_org.yml
  when: runner_type == "organization"
  tags:
    - install
    - uninstall

- include_tasks: collect_info_ent.yml
  when: runner_type == "enterprise"
  tags:
    - install
    - uninstall

- include_tasks: collect_info_repo.yml
  when: runner_type == "repository"
  tags:
    - install
    - uninstall

- include_tasks: install_deps.yml
  when: runner_state|lower == "started" or runner_state|lower == "stopped"
  tags:
    - install

- include_tasks: uninstall_runner.yml
  when: reinstall_runner or runner_state|lower == "absent"
  tags:
    - uninstall

- include_tasks: install_runner.yml
  when: runner_state|lower == "started" or runner_state|lower == "stopped"
  tags:
    - install
